spring:
  profiles:
    active: prod
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

t3t:
  swagger:
    title: "t3t-swagger"
    description: "t3t api documentation"
    version: "v1"