server:
    port: 8081

spring:
  profiles:
    active: dev

  application:
    name: bookstore-service

  eureka:
    instance:
      prefer-ip-address: true
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

t3t:
  swagger:
    title: "t3t-swagger"
    description: "t3t api documentation"
    version: "v1"

  secretKeyManager:
    certKeyPath: ${secretKeyManagerCertKeyPath}
    certKeyType: ${secretKeyManagerCertKeyType}
    appKey: ${secretKeyManagerAppKey}
    password: ${secretKeyManagerPassword}

    secrets:
      databaseName:
        keyId: "e3203972cbf04433b90c752f695d5736"
      databaseServerIpAddress:
        keyId: "62911d2c30064812b2b2c97a8dd90782"
      databaseServerPort:
        keyId: "48e191996aa748938a1edb62652336f4"
      databaseServerUsername:
        keyId: "f008c1d3f87f4f88ae57bd03871eb10d"
      databaseServerPassword:
        keyId: "8a65684780224384a681c3e9035ca7d6"
      objectStorageTenantId:
        keyId: "88e172457ae848f08457db082037d831"
      objectStorageUserName:
        keyId: "b3cfc1e3842342618d710531ff595fc1"
      objectStoragePassword:
        keyId: "346326f7e4da49369eea4472d2f99119"
      objectStorageAuthUrl:
        keyId: "aa39f2ea0fa4424084baf657d34d1fc2"
      reidsServerIpAddress:
        keyId: "10ee8b6140cc49ffa9e7a7c8a2924a3e"
      redisServerPort:
        keyId: "0582f8b117604b7d86e9f3ff26931cde"
      redisServerPassword:
        keyId: "ec1eb8e0706e402cbec8487cbcb86564"